### ISSUE TITLE
Minimum Dovecot version

### ISSUE THREAD

**Issue by evert-mouw** [slusarz/dovecot-fts-flatcurve#2]
dovecot --version
2.3.8

fts-backend-flatcurve.c:21:13: error: ‘event_category_fts’ undeclared here (not in a function);

grep event_category_fts /usr/include/dovecot/*.h
(empty)

I'm not sure when event_category_fts was first included, but dovecot-devel on Oracle Linux 8 gives me no joy. Maybe update the readme or documentation.

Installed Packages
Name         : dovecot-devel
Epoch        : 1
Version      : 2.3.8
Release      : 9.el8
Architecture : x86_64
Size         : 1.7 M
Source       : dovecot-2.3.8-9.el8.src.rpm
Repository   : @System
From repo    : ol8_codeready_builder

**Comment by evert-mouw** [comment]
Follow-up: I've solved this by moving to a newer version of dovecot, using the repo of the dovecot project:
https://repo.dovecot.org/

**Comment by slusarz** [comment]
I believe this was part of 2.3.9, although the category additions are not tracked with versionadded like the events are... https://doc.dovecot.org/admin_manual/list_of_events/

Anyway, the README already indicates the minimum version of Dovecot this code has been known to work with is 2.3.10.  I can make this a bit more explicit in the README.
